name: Render R Markdown Site

on:
  push:
    branches:
      - main
    paths:
      - '**.Rmd'
      - '_site.yml'
      - '_includes/**'

jobs:
  render-site:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up R
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'

    # 3. Cache R packages
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/*.Rmd') }}
        restore-keys: |
          ${{ runner.os }}-r-

    # 4. Set up Pandoc
    - name: Set up Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    # 5. Install required packages
    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('rmarkdown','knitr'), repos='https://cloud.r-project.org')"

    # 6. Clean previous build (optional but ensures updated sidebar)
    - name: Clean docs folder
      run: rm -rf docs

    # 7. Render the site into /docs
    - name: Render site
      run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8", clean = TRUE)'
