name: Render R Markdown Site

on:
  push:
    branches:
      - main    # or your default branch
    paths:
      - '**.Rmd'
      - '_site.yml'
      - '_includes/**'

jobs:
  render-site:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'  # choose your R version

    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install dependencies
      run: |
        Rscript -e "install.packages('knitr', repos='https://cloud.r-project.org')"
        Rscript -e "install.packages('rmarkdown', repos='https://cloud.r-project.org')"
        Rscript -e "install.packages('remotes', repos='https://cloud.r-project.org')"
        


    - name: Render site
      run: Rscript -e 'rmarkdown::render_site(output_dir = "docs")'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # this is the folder created by render_site()
        publish_branch: main # publish to main
        destination_dir: docs   # copy into /docs instead of root
